### ISSUE TITLE
Sandbox full text search is unresponsive, getting: This website is under heavy load (queue full)

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/CredentialRegistry#513] opened 2022-02-10 22:10 UTC
Both the full text search and graph search are unresponsive.

![image](https://user-images.githubusercontent.com/58825866/153505003-070b2442-3fad-43b1-a494-e5739d3c6f82.png)

**Comment by neaf** [comment] 2022-03-01 17:46
I'm sorry to doing that probably again and still not giving you any guarantees, however:

This message means we have couple of long-running requests already, exceeding the number of application server processes. Because of [this resolution](https://github.com/CredentialEngine/CredentialRegistry/issues/512#issuecomment-1055617194) I'm going to close this and other sandbox performance related issue.

It is possible we'll still encounter some problems but there's really no other way to handle those other than eliminating them one by one. If you experience any slow requests, similar errors or complete downtimes, please keep letting me know. We'll keep identifying root causes and hopefully make the system more resilient over time.

**Closed** 2022-03-01 17:47 UTC
Labels: bug, Blocker
