### ISSUE TITLE
Remove check that causes "Resource can only be updated by the original user" errors

### ISSUE THREAD

**Issue by rradonic** [CredentialEngine/CredentialRegistry#164] opened 2017-11-20 15:29 UTC
Looks like this isn't needed anymore and it's causing issues for CE.

**Comment by rsaksida** [comment] 2019-04-16 11:13
@mparsons1953 I remember we ran into an issue related to validating the original submitter for an envelope. Can we disable that check? There's an open PR for that from 2017...

**Comment by cwd-mparsons** [comment] 2019-04-16 17:37
@rsaksida I don't recall the type of error encountered. The current process should only allow the original owner of the data to be the publisher. A third party publisher will have an apiKey that is used, along with the data owner CTID, to validate a transaction. If valid, the registry key for the data owner is used. 
If a different third party publisher is used in the future, the data owner registry key will still be used. 
Or is submitter different than data owner? I would think they might be the same. 
So based on the latter, should this check still be retained?

**Comment by rsaksida** [comment] 2019-04-16 19:54
Currently the API checks the envelope's public key when there's an update. If the key in the update is different from the previous key, it fails (except for keys belonging to "administrative accounts"). That behaviour will also work for publish-on-behalf using the organisation's key. So looks like it's working as intended. I'll close this for now, feel free to reopen it of course if I got something wrong.

**Closed by rsaksida** 2019-04-16 19:54 UTC
