### ISSUE TITLE
"@type : did not match one of the following values: ceterms:QACredentialOrganization

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#52] opened 2017-03-31 00:18 UTC
@coffeejunk @leolara 
I get the error:
**"@type : did not match one of the following values: ceterms:QACredentialOrganization**
when I did a publish for an org with the following type (as attached gist):
**"@type": "ceterms:CredentialOrganization",**

The type is a valid value. 

https://gist.github.com/cwd-mparsons/092f110ce91d59eed9eecd63f2d168f2

Test server url:
http://ctitest.siuccwd.com/organization/21/Southern_Methodist_University

**Comment by coffeejunk** [comment] 2017-03-31 03:48
I'm getting the following

```
Resource JSON Schema validation errors: [

  "_ : The property #/ contains additional properties
  [
    "@context", "ceterms:address", "ceterms:agentPurposeDescription",
    "ceterms:agentType", "ceterms:duns", "ceterms:fein", "ceterms:foundingDate",
    "ceterms:image", "ceterms:ipedsID", "ceterms:name", "ceterms:opeID",
    "ceterms:serviceType", "ceterms:socialMedia", "ceterms:subjectWebpage",
    "ceterms:targetContactPoint"
  ]
  outside of the schema when none are allowed in schema c64d53b6-3b63-57b6-8d38-fea230a9364e#",

  "@type : did not match one of the following values: ceterms:VerificationServiceProfile",
  "ceterms:ctid : is required",
  "ceterms:agentType : did not match the following type: object"

]
```

**Comment by andersoncardoso** [comment] 2017-03-31 16:51
That's probably because of the 'anyOf', what happens on these cases is that the validator will try each of the options from the 'anyOf' until it finds one that validates. If none of the possibilities is valid he shows the errors from the last one (not sure if the last, but the errors for one of them).
The validator (that's not from the app, it's the json-schema validator lib itself, you can test the same with an online validator) doesn't have a way to know which options you are giving is the 'right one' (it can be "any of" them).

**Comment by siuc-nate** [comment] 2017-03-31 17:28
Using this validator
https://json-schema-validator.herokuapp.com/
with the example Mike provided and with the agent JSON:
http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true

I got a series of errors (it looks like one set of errors for each of the types in the "anyOf".  When I reduced the anyOf to just containing CredentialOrganization (just to be sure), I only got two errors:  agentType was being published as a string rather than as a CredentialAlignmentObject, and the foundingDate was in the wrong format (which I believe has been addressed elsewhere).

Upon fixing the agentType, the error was resolved.

Mike, I have checked in the code that fixes the agentType - can you make sure to include it the next time you update the site? Thanks.

**Comment by leolara** [comment] 2017-04-01 10:48
@siuc-nate @cwd-mparsons we have here one of the drawbacks of having 4 groups schemas, instead of one for each type. It makes more difficult to understand errors. In the errors we need to find which one of the rejected AnyOfs is the one that we thought should be accepted

It sems this error is caused by a problem with the date:

```js
  "/anyOf/1" : [ {
      "level" : "error",
      "schema" : {
        "loadingURI" : "#",
        "pointer" : "/definitions/ceterms:CredentialAlignmentObject"
      },
      "instance" : {
        "pointer" : "/ceterms:agentType/0"
      },
      "domain" : "validation",
      "keyword" : "type",
      "message" : "instance type (string) does not match any allowed primitive type (allowed: [\"object\"])",
      "found" : "string",
      "expected" : [ "object" ]
    }, {
      "level" : "error",
      "schema" : {
        "loadingURI" : "#",
        "pointer" : "/definitions/ceterms:foundingDate"
      },
      "instance" : {
        "pointer" : "/ceterms:foundingDate"
      },
      "domain" : "validation",
      "keyword" : "format",
      "attribute" : "date-time",
      "message" : "string \"\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]",
      "value" : "",
      "expected" : [ "yyyy-MM-dd'T'HH:mm:ssZ", "yyyy-MM-dd'T'HH:mm:ss.SSSZ" ]
    } ],
```

**Comment by leolara** [comment] 2017-04-01 10:52
@cwd-mparsons @siuc-nate Also we have an error on agentType. According with the current schema the elements of the array should be objetcs, not strings.

**Comment by leolara** [comment] 2017-04-01 10:54
@cwd-mparsons @siuc-nate @andersoncardoso @coffeejunk 

I can confirm that removing the data fields (foundingDate and agentType) in https://gist.github.com/cwd-mparsons/092f110ce91d59eed9eecd63f2d168f2

makes the validator pass. Those fields are not formated accordingly to the schema, so either the data json or the schema must change

**Comment by leolara** [comment] 2017-04-03 12:30
@cwd-mparsons @siuc-nate please close this issue if my last comment was satisfactory

**Closed** 2017-04-06 16:16 UTC
