### ISSUE TITLE
In production found that an incorrect value is being stored for the envelope_ctdl_type

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#258] opened 2019-08-28 18:47 UTC
I noticed in production that the **envelope_ctdl_type** has a value '@type' rather than an actual ctdl type. 

![image](https://user-images.githubusercontent.com/26332112/63883582-18384c00-c99a-11e9-8a93-d4ce68d53902.png)

**Comment by mparsons-ce** [comment] 2022-05-12 15:10
@excelsior 
I encountered a few envelopes with a envelope_ctdl_type of @type. I need to get the list

**Comment by neaf** [comment] 2022-05-26 14:49
I fixed the data.

Those records weren't fresh so it was not easy to track the root cause there but I'd say most likely it's fixed along the way and those were just left-overs.

New ones appearing would warrant an investigation but for now I'd close the issue.

**Closed** 2022-05-26 15:06 UTC
Labels: bug, High Priority
